{{define "header"}}
    <nav class="navbar">
    <div class="container">
        <ul class="navbar-list">
            <li class="navbar-item"><a class="navbar-link" href="/">KappaStat</a></li>
            <li class="navbar-item"><a class="navbar-link" href="/stat">Stats</a></li>
            <li class="navbar-item"><a class="navbar-link" href="/following">Following</a></li>
        </ul>
    </div>
</nav>
<div class="spacer"></div>
{{end}}
