{{define "head"}}
<head>
        <meta charset="utf-8">
        <link href="skeleton.css" rel="stylesheet">
        <link href="normalize.css" rel="stylesheet">
        <link href="theme.css" rel="stylesheet">
        <script type="text/javascript"
                src="https://www.google.com/jsapi?autoload={
                'modules':[{
                'name':'visualization',
                'version':'1.0',
                'packages':['line','corechart']
                }]
                }"></script>
        <script type="text/javascript" src="//code.jquery.com/jquery-2.1.4.min.js"></script>
</head>
{{end}}
